# Generated by Django 3.0.1 on 2019-12-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Ingrese el URL de la imagen', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('tipo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese su direccion', max_length=100)),
                ('direccion', models.CharField(help_text='Ingrese su nombre completo', max_length=100)),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ingrese su descripcion', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Adjunte una breve descripcion del Rol', max_length=100)),
                ('rol', models.CharField(help_text='Aqui van los Roles', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.CharField(help_text='Ingrese su direccion', max_length=100)),
                ('nombre_completo', models.CharField(help_text='Ingrese su nombre completo', max_length=100)),
                ('correo', models.EmailField(help_text='Ingrese su direccion', max_length=100)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('rolfk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedatos.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese el titulo de la noticia', max_length=50)),
                ('descripcion', models.CharField(help_text='Ingrese su descripcion', max_length=800)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedatos.Lugar')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedatos.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='regla',
            field=models.ManyToManyField(help_text='Seleccione una regla para este Lugar', to='basedatos.Regla'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Ingrese su descripcion', max_length=200)),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedatos.Lugar')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedatos.Persona')),
            ],
        ),
    ]
